---
version: "2"
checks:
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  complex-logic:
    enabled: true
    config:
      threshold: 20
  method-count:
    config:
      threshold: 35
  method-lines:
    config:
      threshold: 100
  return-statements:
    config:
      threshold: 10
plugins:
  markdownlint:
    enabled: true
  radon: 
    enabled: true
    config: 
      threshold: C
      python_version: 3
  pep8:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - ftl_api/**
        - tests/**
  structure:
    enabled: true
  duplication:
    enabled: true
exclude_patterns:
  - '**/__pycache__/'
  - '**/.pytest_cache/'
  - '**/config.py' # Excluded as each microservice has it's own configs
