component:
  name: aws_api_gateway_deployment
  dependsOn:
    - aws_api_gateway_rest_api
    - aws_api_gateway_msa_latest
    - aws_api_gateway_msa_ping
    # - aws_api_gateway_msa_ping_resources
    - aws_api_gateway_msa_root
    - aws_api_gateway_msa_status
    - aws_api_gateway_msa_uuid
    - aws_api_gateway_mgr_member
    - aws_api_gateway_mgr_account
    - aws_api_gateway_mgr_microservice
    - aws_api_gateway_mgr_transaction_type
    - aws_api_gateway_mgr_transaction
    - aws_api_gateway_mgr_message
    - aws_api_gateway_mgr_message_category
    - aws_api_gateway_mgr_message_definition
    - aws_api_gateway_mgr_message_target
    - aws_api_gateway_mgr_message_parser
    - aws_api_gateway_mgr_dashboard
    - aws_api_gateway_mgr_provider
    - aws_api_gateway_mgr_provider_category
    - aws_api_gateway_mgr_provider_subcategory
    - aws_api_gateway_mgr_config
    - aws_api_gateway_mgr_build
