component:
  name: aws_api_gateway_mgr_message_target
  dependsOn:
    - aws_api_gateway_rest_api
    - aws_api_gateway_authorizer
    - aws_api_gateway_vpc_link_mgr_ops
    - aws_lb_mgr_ops
    - aws_lb_target_group_mgr_message_target
    - aws_api_gateway_mgr_message
